# Generated by Django 4.0.6 on 2022-09-06 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_recipe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('about', models.TextField()),
                ('diet', models.CharField(choices=[('None', 'No restrictions'), ('Keto', 'Ketogenic'), ('Paleo', 'Paleolithic'), ('ATK', 'Atkins'), ('Lo-F', 'Low-Fat'), ('Raw', 'Raw Food'), ('LCal', 'Low Calorie'), ('LCal', 'Low Calorie'), ('MediT', 'Mediterranean'), ('DASH', 'dietary approaches to stop hypertension'), ('Anti-A', 'Anti-Inflammatory')], default='None', max_length=100)),
                ('favorites', models.ManyToManyField(to='main_app.recipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
