# Generated by Django 4.0.6 on 2022-09-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_recipephoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipephoto',
            old_name='cat',
            new_name='recipe',
        ),
    ]
