# Generated by Django 4.0.6 on 2022-09-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_cat_recipephoto_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('U', 'unknown'), ('P', 'Protein'), ('O', 'Oil'), ('V', 'Vegetable'), ('S', 'Starch'), ('F', 'Fruit'), ('W', 'Sweetener'), ('M', 'Meet'), ('H', 'Herbs and Spices')], max_length=10)),
            ],
        ),
    ]
