# Generated by Django 4.0.6 on 2022-09-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('V', 'Vegetable'), ('P', 'Protein'), ('M', 'Meet'), ('U', 'unknown'), ('W', 'Sweetener'), ('H', 'Herbs and Spices'), ('S', 'Starch'), ('F', 'Fruit'), ('O', 'Oil')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.ingredient'),
        ),
    ]
